<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="CAVICSRGXFTVT2" name="CTD_Unprocessed_Events_Endpoint.Tombstone_insert_and_delete" tests="1" failures="1" timestamp="27 Jun 2019 03:35:45 GMT" time="43.313" errors="0">
  <testcase name="insertcl" time="43.313" classname="CTD_Unprocessed_Events_Endpoint.Tombstone_insert_and_delete">
    <failure type="java.lang.AssertionError" message="expected [867670002] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [867670002] but found [null]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at CTD_Dynamic_Adapter_Endpoint.Adapter.tombstoneadult(Adapter.java:589)
at CTD_Unprocessed_Events_Endpoint.Tombstone_insert_and_delete.inscsperchars(Tombstone_insert_and_delete.java:288)
at CTD_Unprocessed_Events_Endpoint.Tombstone_insert_and_delete.insert_csperchars(Tombstone_insert_and_delete.java:219)
at CTD_Unprocessed_Events_Endpoint.Tombstone_insert_and_delete.insertcl(Tombstone_insert_and_delete.java:106)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- insertcl -->
</testsuite> <!-- CTD_Unprocessed_Events_Endpoint.Tombstone_insert_and_delete -->
